### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by chengzhongyi8** [HIT-ImmunologyLab/DBSCAN-SWA#29]
Hi,

Thanks for developing such a powerful tool. I installed this following the pipeline, and `python <path>/dbscan-swa.py --h` shows the correct output. However, when I ran it on my own data, I encountered an issue:
```
/var/spool/slurmd/job815759/slurm_script: ligne15: activate: Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File "/store/tool/DBSCAN-SWA/bin/dbscan-swa.py", line 2841, in <module>
    if os.path.getsize(c_inputfile_bac)>0:
  File "/home/conda/envs/prokka/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'output/results/DBSCAN_28/DBSCAN_28.fna'
```
And my command is:
```
python /store/tool/DBSCAN-SWA/bin/dbscan-swa.py \
    --input prokka.output/rename.gbk \
    --output output \
    --prefix DBSCAN \
    --thread_num 16
```
When I ran it on the test fasta (test/NC_007054.gb), there is no error:
```
Reported 7108 pairwise alignments, 7165 HSPs.
63 queries aligned.
start to visualize the results!
Running time: 0.42442688544591267 minutes! Finished prediction in /store/DBSCAN-SWA/test/test.output
```
Can you help me fix this issue? Thanks in advance!

**Comment by isidoramorel** [comment]
@chengzhongyi8 did you ever find a solution for this? it happens to me only with some random gbk files and I can't figure out why
