### ISSUE TITLE
Error parsing prophage feature value

### ISSUE THREAD

**Issue by peng-ye** [HIT-ImmunologyLab/DBSCAN-SWA#7]
Dear Author,

Would you please help sort this error out? Thanks.

**In the STDOUT:**
step7:start to annotate the predicted prophage regions parse prophage feature value error!

**In the STDERR:**
\# There is no \*blastn\* files in the _prophage_annotation_ folder

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/pengye/Software/anaconda3/envs/prokka/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/pengye/Software/anaconda3/envs/prokka/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pengye/Software/DBSCAN-SWA/bin/dbscan-swa.py", line 1659, in parse_prophage_blastn_phagedb_6
    with open(outfile) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/prophage_annotation/prophage_blastn_phage'

Traceback (most recent call last):
  File "/home/pengye/Software/DBSCAN-SWA/bin/dbscan-swa.py", line 2706, in <module>
    predict_prophage(strain_id,inputfile_bac,outdir,add_annotation,prefix)
  File "/home/pengye/Software/DBSCAN-SWA/bin/dbscan-swa.py", line 2574, in predict_prophage
    visualize(save_prophage_file,save_prophage_nucl_file,save_prophage_protein_file,prophage_region_annotate_dir,add_annotation,templeate_file,save_html_file)
  File "/home/pengye/Software/DBSCAN-SWA/bin/dbscan-swa.py", line 2356, in visualize
    with open(prophage_hit_phage_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'results/prophage_annotation/prophage_annotate_phage_details.txt'

**Comment by gancao** [comment]
Hello, @peng-ye 

Could you please provide the sequence file that met the error of it is convenient? or you can give me a screenshot of the results directorys? The possible reason was that blastn was not correctly created

**Comment by gancao** [comment]
I have updated dbscan-swa.py on https://github.com/gancao/DBSCAN-SWA-1

**Comment by peng-ye** [comment]
> I have updated dbscan-swa.py on https://github.com/gancao/DBSCAN-SWA-1

Thanks for this update, especially the inclusion of "thread_num" in the args list. Now an updated version of that script has been proposed in the repository.
